// C4D-DialogResource
DIALOG IDD_DIALOG_SETTINGS
{
  NAME IDS_DIALOG_TITLE; CENTER_V; ALIGN_LEFT; 
  
  GROUP IDC_GROUP_WRAPPER
  {
    NAME IDS_GROUP_WRAPPER; ALIGN_TOP; SCALE_H; 
    BORDERSIZE 4, 4, 4, 4; 
    COLUMNS 1;
    SPACE 4, 4;
    
    GROUP IDC_GROUP_SETTINGS
    {
      NAME IDS_GROUP_SETTINGS; ALIGN_TOP; CENTER_H; 
      BORDERSIZE 5, 5, 5, 5; 
      COLUMNS 1;
      SPACE 4, 4;
      
      CHECKBOX IDC_CHK_OPTIMIZE { NAME IDS_CHECK; ALIGN_TOP; ALIGN_LEFT;  }
      CHECKBOX IDC_CHK_CENTER { NAME IDS_CHECK2; ALIGN_TOP; ALIGN_LEFT;  }
      SEPARATOR { SCALE_H; }
      CHECKBOX IDC_CHK_DELETEORIG { NAME IDS_CHECK4; ALIGN_TOP; ALIGN_LEFT;  }
      GROUP IDC_STATIC
      {
        ALIGN_TOP; ALIGN_LEFT; 
        BORDERSIZE 16, 0, 0, 0; 
        COLUMNS 1;
        SPACE 4, 4;
        
        CHECKBOX IDC_CHK_HIDE { NAME IDS_CHECK1; ALIGN_TOP; ALIGN_LEFT;  }
      }
      SEPARATOR { SCALE_H; }
      CHECKBOX IDC_CHK_KEEPNORMALTAG { NAME IDS_CHECK3; ALIGN_TOP; ALIGN_LEFT;  }
      GROUP IDC_STATIC
      {
        NAME IDS_STATIC1; ALIGN_TOP; ALIGN_LEFT; 
        BORDERSIZE 16, 0, 0, 0; 
        COLUMNS 1;
        SPACE 4, 4;
        
        CHECKBOX IDC_CHK_RENORMALIZE { NAME IDS_CHECK5; ALIGN_TOP; ALIGN_LEFT;  }
      }
    }
    SEPARATOR { SCALE_H; }
    GROUP IDC_GROUP_BUTTONS
    {
      NAME IDS_GROUP_BUTTONS; ALIGN_TOP; CENTER_H; 
      BORDERSIZE 0, 0, 0, 0; 
      COLUMNS 2;
      SPACE 4, 4;
      
      BUTTON IDC_BUTTON_CANCEL { NAME IDS_BUTTON_CANCEL; ALIGN_TOP; CENTER_H; }
      BUTTON IDC_BUTTON_DOIT { NAME IDS_BUTTON_DOIT; ALIGN_TOP; CENTER_H; }
    }
    GROUP IDC_DUMMY
    {
      NAME IDS_DUMMY; ALIGN_TOP; SCALE_H; 
      BORDERSIZE 0, 0, 0, 0; 
      COLUMNS 1;
      SPACE 4, 4;
      
      
    }
  }
}