// C4D-DialogResource
DIALOG IDD_DIALOG_SETTINGS
{
  NAME IDS_DIALOG_TITLE; CENTER_V; ALIGN_LEFT; 
  
  GROUP IDC_GROUP_WRAPPER
  {
    NAME IDS_GROUP_WRAPPER; SCALE_V; SCALE_H; 
    BORDERSIZE 4, 4, 4, 4; 
    COLUMNS 1;
    SPACE 4, 4;
    
    GROUP IDC_GROUP_SETTINGS
    {
      NAME IDS_GROUP_ENTRYUI; SCALE_V; SCALE_H; 
      BORDERSIZE 2, 2, 2, 2; 
      COLUMNS 2;
      SPACE 4, 4;
      
      STATICTEXT IDC_STATIC_SEARCH { NAME IDS_STATIC_SEARCH; CENTER_V; ALIGN_RIGHT; }
      MULTILINEEDIT IDC_EDIT_SEARCH
      { 
        SCALE_V; SCALE_H; SIZE 70, 0; 
        MONOSPACED; SYNTAXCOLOR; PYTHON; STATUSBAR; 
      }
      STATICTEXT IDC_STATIC_REPLACE { NAME IDS_STATIC_REPLACE; CENTER_V; ALIGN_RIGHT; }
      MULTILINEEDIT IDC_EDIT_REPLACE
      { 
        SCALE_V; SCALE_H; SIZE 70, 0; 
        MONOSPACED; SYNTAXCOLOR; PYTHON; STATUSBAR; 
      }
    }
    GROUP IDC_STATIC
    {
      NAME IDS_GROUP_SETTINGS_REGEX; ALIGN_TOP; ALIGN_LEFT; 
      BORDERSTYLE BORDER_NONE; BORDERSIZE 77, 0, 4, 0; 
      ROWS 1;
      
      CHECKBOX IDC_CHECK_IGNORECASE { NAME IDS_CHECK_IGNORECASE; ALIGN_TOP; ALIGN_LEFT;  }
      CHECKBOX IDC_CHECK_MULTILINE { NAME IDS_CHECK_MULTILINE; ALIGN_TOP; ALIGN_LEFT;  }
      CHECKBOX IDC_CHECK_DOTALL { NAME IDS_CHECK_DOTALL; ALIGN_TOP; ALIGN_LEFT;  }
      CHECKBOX IDC_CHECK_VERBOSE { NAME IDS_CHECK_VERBOSE; ALIGN_TOP; ALIGN_LEFT;  }
    }
    GROUP IDC_GROUP_SETTINGS2
    {
      NAME IDS_GROUP_SETTINGS_TARGET; ALIGN_TOP; ALIGN_LEFT; 
      BORDERSIZE 77, 0, 0, 0; 
      COLUMNS 1;
      SPACE 4, 4;
      
      CHECKBOX IDC_CHECK_SELECTIONONLY { NAME IDS_CHECK_SELECTIONONLY; ALIGN_TOP; ALIGN_LEFT;  }
    }
    SEPARATOR { SCALE_H; }
    GROUP IDC_GROUP_BUTTONS
    {
      NAME IDS_GROUP_BUTTONS; ALIGN_TOP; CENTER_H; 
      BORDERSIZE 0, 0, 0, 0; 
      COLUMNS 2;
      SPACE 4, 4;
      
      BUTTON IDC_BUTTON_CANCEL { NAME IDS_BUTTON_CANCEL; ALIGN_TOP; CENTER_H; }
      BUTTON IDC_BUTTON_DOIT { NAME IDS_BUTTON_DOIT; ALIGN_TOP; CENTER_H; }
    }
    GROUP IDC_DUMMY
    {
      NAME IDS_DUMMY; ALIGN_TOP; SCALE_H; 
      BORDERSIZE 0, 0, 0, 0; 
      COLUMNS 1;
      SPACE 4, 4;
      
      
    }
  }
}