// C4D-DialogResource
DIALOG IDD_DIALOG_SETTINGS
{
  NAME IDS_DIALOG_TITLE; CENTER_V; ALIGN_LEFT; 
  
  GROUP IDC_GROUP_WRAPPER
  {
    NAME IDS_GROUP_WRAPPER; ALIGN_TOP; SCALE_H; 
    BORDERSIZE 4, 4, 4, 4; 
    COLUMNS 1;
    SPACE 4, 4;
    
    GROUP IDC_GROUP_SETTINGS
    {
      NAME IDS_GROUP_SETTINGS; ALIGN_TOP; SCALE_H; 
      BORDERSIZE 5, 5, 5, 0; 
      COLUMNS 3;
      SPACE 4, 4;
      
      STATICTEXT IDC_STATIC_TARGET { NAME IDS_STATIC_TARGET; CENTER_V; ALIGN_LEFT; }
      EDITTEXT IDC_EDIT_TARGET
      { CENTER_V; SCALE_H; SIZE 70, 0; }
      BUTTON IDC_BUTTON_GETOBJ { NAME IDS_BUTTON_GETOBJ; ALIGN_TOP; ALIGN_LEFT; }
    }
    GROUP IDC_STATIC
    {
      NAME IDS_STATIC_SETTINGS4; ALIGN_TOP; SCALE_H; 
      BORDERSTYLE BORDER_NONE; BORDERSIZE 5, 0, 5, 0; 
      COLUMNS 2;
      
      STATICTEXT IDC_STATIC_UPAXIS { NAME IDS_STATIC_UPAXIS; CENTER_V; ALIGN_LEFT; }
      COMBOBOX IDC_COMBO_UPAXIS
      {
        ALIGN_TOP; SCALE_H; SIZE 150, 0; 
        CHILDS
        {
          1, IDS_X; 
          2, IDS_Y; 
          3, IDS_Z; 
        }
      }
    }
    SEPARATOR { SCALE_H; }
    GROUP IDC_GROUP_SETTINGS2
    {
      NAME IDS_GROUP_SETTINGS2; ALIGN_TOP; SCALE_H; 
      BORDERSIZE 5, 0, 5, 0; 
      COLUMNS 2;
      SPACE 4, 4;
      
      STATICTEXT IDC_STATIC_MODE { NAME IDS_STATIC_MODE; CENTER_V; ALIGN_LEFT; }
      COMBOBOX IDC_COMBO_MODE
      {
        ALIGN_TOP; SCALE_H; SIZE 150, 0; 
        CHILDS
        {
          1, IDS_NORMAL; 
          2, IDS_MANUAL; 
          3, IDS_X; 
          4, IDS_Y; 
          5, IDS_Z; 
          6, IDS_X_LOCAL; 
          7, IDS_Y_LOCAL; 
          8, IDS_Z_LOCAL; 
        }
      }
    }
    GROUP IDC_GROUP_SETTINGS3
    {
      NAME IDS_GROUP_SETTINGS2; SCALE_V; SCALE_H; 
      BORDERSIZE 5, 0, 5, 5; 
      COLUMNS 2;
      SPACE 4, 4;
      
      STATICTEXT IDC_STATIC_MANUAL { NAME IDS_STATIC_MANUAL; CENTER_V; CENTER_H; }
      GROUP IDC_GROUP_MANUAL
      {
        NAME IDS_GROUP_MANUAL; ALIGN_TOP; SCALE_H; 
        BORDERSIZE 0, 0, 0, 0; 
        COLUMNS 3;
        SPACE 4, 4;
        
        EDITNUMBERARROWS IDC_EDIT_X
        { CENTER_V; SCALE_H; SIZE 70, 0; }
        EDITNUMBERARROWS IDC_EDIT_Y
        { CENTER_V; SCALE_H; SIZE 70, 0; }
        EDITNUMBERARROWS IDC_EDIT_Z
        { CENTER_V; SCALE_H; SIZE 70, 0; }
      }
    }
    SEPARATOR { SCALE_H; }
    GROUP IDC_GROUP_BUTTONS
    {
      NAME IDS_GROUP_BUTTONS; ALIGN_TOP; CENTER_H; 
      BORDERSIZE 0, 0, 0, 0; 
      COLUMNS 2;
      SPACE 4, 4;
      
      BUTTON IDC_BUTTON_CANCEL { NAME IDS_BUTTON_CANCEL; ALIGN_TOP; CENTER_H; }
      BUTTON IDC_BUTTON_DOIT { NAME IDS_BUTTON_DOIT; ALIGN_TOP; CENTER_H; }
    }
    GROUP IDC_DUMMY
    {
      NAME IDS_DUMMY; ALIGN_TOP; SCALE_H; 
      BORDERSIZE 0, 0, 0, 0; 
      COLUMNS 1;
      SPACE 4, 4;
      
      
    }
  }
}